classes:
  RobotVisualisation:
    scene:
      width: 4000
      height: 1500
    beams:
      top:
        width: 4000
        height: 160
        color: "#555555"
      left:
        width: &arm_width 40
        height: &arm_height 1500
        color: green
      right:
        width: *arm_width
        height: *arm_height
        color: red