classes:
  RobotVisualisation:
    scene:
      width: 4000
      height: 1500
    beams:
      top:
        width: 4000
        height: 160
        color: "#555555"
      left:
        width: &arm_width 40
        height: &arm_height 1500
        color: green
      right:
        width: *arm_width
        height: *arm_height
        color: red
  RimoServer:
    statusAddress: &statusAddr "ipc:///tmp/rimoStatus"
    commandAddress: &commandAddr "ipc:///tmp/rimoCommand"
  RimoClient:
    statusAddress: *statusAddr
    commandAddress: *commandAddr
  Contec:
    ipAddress: "10.1.1.101"
    port : 502
    slaveId: 0
    nDI : 16
    nDO : 8
    nAI : 0 #so far not used
  ControlPanel:
    comm:
      type: "serial"
      serial:
        port: "/dev/ttyACM0"
        baudRate: "BAUD_115200" #libserial naming
        characterSize: "CHAR_SIZE_8"
        flowControl: "FLOW_CONTROL_NONE"
        parity: "PARITY_NONE"
        stopBits: "STOP_BITS_1"
        readTimeoutMS: 200
        lineTerminator: "\\n"
    processing:
      movingAverageDepth: 5
      baselineSamples: 50
      buttonDebounceSamples: 3
  MotorControl:
    model: "AR-KD2"
    transport:
      type: "rawTcpRtu" # default path for motors
      #type: "serialRtu" # default path for motors
      tcp:
        host: "10.1.1.102"
        port: 4002
      serial:
        device: "/dev/ttyr01"
        baud: 115200
        parity: "E"
        dataBits: 8
        stopBits: 1
    responseTimeoutMS: 100
    connectTimeoutMS: 100
    interRequestDelayMS: 3
    motors:
      XLeft:
        address: 1
        runCurrent: 500
        stopCurrent: 100
        startingSpeed: 100
        overloadWarning: 10
        overloadAlarm: 300
        excessivePositionDeviationWarning: 500
        excessivePositionDeviationAlarm: 700
#      XRight:
#        address: 2
#        groupId: 1
#        runCurrent: 1000
#        stopCurrent: 500
#        startingSpeed: 100
#        overloadWarning: 1000
#        overloadAlarm: 1200
#        excessivePositionDeviationWarning: 500
#        excessivePositionDeviationAlarm: 700
      YLeft:
        address: 2
        runCurrent: 500
        stopCurrent: 0
        startingSpeed: 100
        overloadWarning: 10
        overloadAlarm: 300
        excessivePositionDeviationWarning: 500
        excessivePositionDeviationAlarm: 700
#      YRight:
#        address: 4
#        groupId: 1
#        runCurrent: 1000
#        stopCurrent: 500
#        startingSpeed: 100
#        overloadWarning: 1000
#        overloadAlarm: 1200
#        excessivePositionDeviationWarning: 500
#        excessivePositionDeviationAlarm: 700
#      ZLeft:
#        address: 5
#        groupId: 1
#        runCurrent: 1000
#        stopCurrent: 500
#        startingSpeed: 100
#        overloadWarning: 1000
#        overloadAlarm: 1200
#        excessivePositionDeviationWarning: 500
#        excessivePositionDeviationAlarm: 700
#      ZRight:
#        address: 6
#        groupId: 1
#        runCurrent: 1000
#        stopCurrent: 500
#        startingSpeed: 100
#        overloadWarning: 1000
#        overloadAlarm: 1200
#        excessivePositionDeviationWarning: 500
#        excessivePositionDeviationAlarm: 700
  Machine:
    loopIntervalMS: 60
    updateIntervalMS: 200
    motion:
      stepsPerRevolution: 1000
      neutralAxisActivationThreshold: 0.05
      speedUpdateAxisDeltaThreshold: 0.02
      axes:
        leftArmX:
          invertAxis: false
          speedUpdateAxisDeltaThreshold: 0.02
          maxLinearSpeedMmPerSec: 150.0
          stepsPerMm: 14.15
          acceleration001MsPerKHz: 50000
          deceleration001MsPerKHz: 50000
        leftArmY:
          invertAxis: false
          speedUpdateAxisDeltaThreshold: 0.02
          maxLinearSpeedMmPerSec: 150.0
          stepsPerMm: 20
          acceleration001MsPerKHz: 50000
          deceleration001MsPerKHz: 50000
        rightArmX:
          invertAxis: false
          speedUpdateAxisDeltaThreshold: 0.02
          maxLinearSpeedMmPerSec: 80.0
          stepsPerMm: 100.0
          acceleration001MsPerKHz: 24575
          deceleration001MsPerKHz: 24575
        rightArmY:
          invertAxis: false
          speedUpdateAxisDeltaThreshold: 0.02
          maxLinearSpeedMmPerSec: 80.0
          stepsPerMm: 100.0
          acceleration001MsPerKHz: 24575
          deceleration001MsPerKHz: 24575
        gantryZ:
          invertAxis: false
          speedUpdateAxisDeltaThreshold: 0.02
          maxLinearSpeedMmPerSec: 80.0
          stepsPerMm: 100.0
          acceleration001MsPerKHz: 24575
          deceleration001MsPerKHz: 24575
    inputMapping:
      safetyON : 8
      button1 : 9
      button2 : 10
      tclProx : 0
      tclOpen : 2
      tclClose: 3
      tcrProx: 4
      tcrOpen: 5
      tcrClose: 6
    outputMapping:
      toolChangerLeft: 0
      toolChangerRight: 1
      light1 : 2
      light2 : 3
